INSERT OR IGNORE INTO `events` (
  `id`,
  `title`,
  `slug`,
  `description`,
  `image_url`,
  `start_date`,
  `end_date`,
  `price`,
  `capacity`,
  `location`,
  `instructor`,
  `is_active`,
  `updated_at`
) VALUES
  (
    'workshop-2026-04-12',
    'Beginner Sewing Foundations',
    'beginner-sewing-workshop',
    'A beginner-friendly workshop covering machine setup, straight seams, and confidence-building projects.',
    NULL,
    1776016800000,
    NULL,
    35,
    18,
    'ReLUXURY Studio, Maumelle',
    'Ashley Reed',
    true,
    cast(unixepoch('subsecond') * 1000 as integer)
  ),
  (
    'workshop-2026-04-26',
    'Denim Hem Clinic',
    'denim-hem-clinic',
    'Bring your jeans and leave with perfect hems. Learn measurements, pinning technique, and professional finishing.',
    NULL,
    1777226400000,
    NULL,
    30,
    14,
    'ReLUXURY Studio, Maumelle',
    'Ashley Reed',
    true,
    cast(unixepoch('subsecond') * 1000 as integer)
  ),
  (
    'workshop-2026-05-03',
    'Closet Refresh Alteration Lab',
    'closet-refresh-alteration-lab',
    'Learn quick fit fixes for everyday pieces and leave with a practical alteration checklist for your wardrobe.',
    NULL,
    1777831200000,
    NULL,
    40,
    16,
    'ReLUXURY Studio, Maumelle',
    'Ashley Reed',
    true,
    cast(unixepoch('subsecond') * 1000 as integer)
  ),
  (
    'workshop-2026-05-10',
    'Sewing 101: First Garment Start',
    'sewing-101-first-garment-start',
    'Pattern basics, cutting flow, and first-garment construction fundamentals for new makers.',
    NULL,
    1778436000000,
    NULL,
    45,
    20,
    'ReLUXURY Studio, Maumelle',
    'Ashley Reed',
    true,
    cast(unixepoch('subsecond') * 1000 as integer)
  ),
  (
    'workshop-2026-05-17',
    'Zipper & Button Repair Session',
    'zipper-button-repair-session',
    'Hands-on repair workshop focused on replacing zippers, reinforcing seams, and button restoration.',
    NULL,
    1779040800000,
    NULL,
    30,
    15,
    'ReLUXURY Studio, Maumelle',
    'Ashley Reed',
    true,
    cast(unixepoch('subsecond') * 1000 as integer)
  ),
  (
    'workshop-2026-05-24',
    'Summer Dress Fit & Finish',
    'summer-dress-fit-finish',
    'Workshop focused on dress fit adjustments, lining touch-ups, and clean finishing techniques.',
    NULL,
    1779645600000,
    NULL,
    50,
    12,
    'ReLUXURY Studio, Maumelle',
    'Ashley Reed',
    true,
    cast(unixepoch('subsecond') * 1000 as integer)
  ),
  (
    'workshop-2026-06-07',
    'Upcycle Your Favorite Piece',
    'upcycle-your-favorite-piece',
    'Creative sewing workshop that transforms one tired garment into a fresh, wearable statement piece.',
    NULL,
    1780855200000,
    NULL,
    55,
    14,
    'ReLUXURY Studio, Maumelle',
    'Ashley Reed',
    true,
    cast(unixepoch('subsecond') * 1000 as integer)
  ),
  (
    'workshop-2026-06-21',
    'Intermediate Pattern Hacking',
    'intermediate-pattern-hacking',
    'For returning students: modify base patterns for custom silhouettes, sleeves, and elevated fit.',
    NULL,
    1782064800000,
    NULL,
    60,
    12,
    'ReLUXURY Studio, Maumelle',
    'Ashley Reed',
    true,
    cast(unixepoch('subsecond') * 1000 as integer)
  );
