/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AlterationsRouteImport } from './routes/alterations'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminWorkshopsWorkshopIdRouteImport } from './routes/admin.workshops.$workshopId'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin.orders.$orderId'
import { Route as AdminAlterationsAlterationIdRouteImport } from './routes/admin.alterations.$alterationId'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AlterationsRoute = AlterationsRouteImport.update({
  id: '/alterations',
  path: '/alterations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkshopsWorkshopIdRoute =
  AdminWorkshopsWorkshopIdRouteImport.update({
    id: '/workshops/$workshopId',
    path: '/workshops/$workshopId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlterationsAlterationIdRoute =
  AdminAlterationsAlterationIdRouteImport.update({
    id: '/alterations/$alterationId',
    path: '/alterations/$alterationId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/alterations': typeof AlterationsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/shop': typeof ShopRouteWithChildren
  '/events/$slug': typeof EventsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin/alterations/$alterationId': typeof AdminAlterationsAlterationIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/workshops/$workshopId': typeof AdminWorkshopsWorkshopIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/alterations': typeof AlterationsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/shop': typeof ShopRouteWithChildren
  '/events/$slug': typeof EventsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin/alterations/$alterationId': typeof AdminAlterationsAlterationIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/workshops/$workshopId': typeof AdminWorkshopsWorkshopIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/alterations': typeof AlterationsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/shop': typeof ShopRouteWithChildren
  '/events/$slug': typeof EventsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin/alterations/$alterationId': typeof AdminAlterationsAlterationIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/workshops/$workshopId': typeof AdminWorkshopsWorkshopIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/alterations'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/events'
    | '/login'
    | '/shop'
    | '/events/$slug'
    | '/shop/$slug'
    | '/admin/alterations/$alterationId'
    | '/admin/orders/$orderId'
    | '/admin/workshops/$workshopId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/alterations'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/events'
    | '/login'
    | '/shop'
    | '/events/$slug'
    | '/shop/$slug'
    | '/admin/alterations/$alterationId'
    | '/admin/orders/$orderId'
    | '/admin/workshops/$workshopId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/alterations'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/events'
    | '/login'
    | '/shop'
    | '/events/$slug'
    | '/shop/$slug'
    | '/admin/alterations/$alterationId'
    | '/admin/orders/$orderId'
    | '/admin/workshops/$workshopId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlterationsRoute: typeof AlterationsRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ShopRoute: typeof ShopRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alterations': {
      id: '/alterations'
      path: '/alterations'
      fullPath: '/alterations'
      preLoaderRoute: typeof AlterationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workshops/$workshopId': {
      id: '/admin/workshops/$workshopId'
      path: '/workshops/$workshopId'
      fullPath: '/admin/workshops/$workshopId'
      preLoaderRoute: typeof AdminWorkshopsWorkshopIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alterations/$alterationId': {
      id: '/admin/alterations/$alterationId'
      path: '/alterations/$alterationId'
      fullPath: '/admin/alterations/$alterationId'
      preLoaderRoute: typeof AdminAlterationsAlterationIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlterationsAlterationIdRoute: typeof AdminAlterationsAlterationIdRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  AdminWorkshopsWorkshopIdRoute: typeof AdminWorkshopsWorkshopIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlterationsAlterationIdRoute: AdminAlterationsAlterationIdRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminWorkshopsWorkshopIdRoute: AdminWorkshopsWorkshopIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AlterationsRoute: AlterationsRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRouteWithChildren,
  LoginRoute: LoginRoute,
  ShopRoute: ShopRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
