import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import dotenv from "dotenv";
import { defineConfig } from "drizzle-kit";

const getBaseDir = () => {
  // oxlint-disable-next-line unicorn/prefer-module
  if (typeof __dirname !== "undefined") {
    // oxlint-disable-next-line unicorn/prefer-module
    return __dirname;
  }
  try {
    // oxlint-disable-next-line unicorn/no-typeof-undefined, unicorn/prefer-import-meta-properties
    if (typeof import.meta !== "undefined" && import.meta.url) {
      // oxlint-disable-next-line unicorn/prefer-import-meta-properties
      return path.dirname(fileURLToPath(import.meta.url));
    }
  } catch {
    // Fallback if import.meta.url is not defined in this environment
  }

  const cwd = process.cwd();
  if (cwd.endsWith("packages/db")) {
    return cwd;
  }
  return path.resolve(cwd, "packages/db");
};

const baseDir = getBaseDir();

dotenv.config({
  path: path.resolve(baseDir, "../../apps/web/.env"),
});

// Find the local D1 SQLite file generated by Miniflare/Alchemy
const getLocalD1Path = () => {
  const d1Dir = path.resolve(
    baseDir,
    "../../.alchemy/miniflare/v3/d1/miniflare-D1DatabaseObject"
  );
  if (!fs.existsSync(d1Dir)) {
    return null;
  }

  const files = fs.readdirSync(d1Dir);
  // Filter for sqlite files, excluding metadata.sqlite and journal/shm/wal files
  const sqliteFiles = files.filter(
    (f) => f.endsWith(".sqlite") && f !== "metadata.sqlite"
  );

  if (sqliteFiles.length === 0) {
    return null;
  }

  // Sort by size descending since the active database will have schema/data and be larger
  const sorted = sqliteFiles
    .map((file) => {
      const filePath = path.join(d1Dir, file);
      const stat = fs.statSync(filePath);
      return { file, filePath, size: stat.size };
    })
    .toSorted((a, b) => b.size - a.size);

  return sorted[0]?.filePath ?? null;
};

const localDbPath = getLocalD1Path();

export default defineConfig(
  localDbPath
    ? {
        dbCredentials: {
          url: localDbPath,
        },
        dialect: "sqlite",
        out: "./src/migrations",
        schema: "./src/schema",
      }
    : {
        dbCredentials: {
          accountId: process.env.CLOUDFLARE_ACCOUNT_ID ?? "",
          databaseId: process.env.CLOUDFLARE_DATABASE_ID ?? "",
          token: process.env.CLOUDFLARE_D1_TOKEN ?? "",
        },
        dialect: "sqlite",
        driver: "d1-http",
        out: "./src/migrations",
        schema: "./src/schema",
      }
);
